apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pr-elt-business
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "docker.io/wesleyst5/spark-operator:v3.0.0-aws"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/spark-operator-processing-job-batch.py"  
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20  
  sparkConf:
    spark.jars.packages: "org.apache.hadoop:hadoop-aws:2.7.3"
  hadoopConf:
    fs.s3a.endpoint: s3.us-east-2.amazonaws.com    
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  driver:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: default
  executor:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.0.0